Dev: Address ansible sanity, lint and unit test failure when testing with ansible>=3
There were quite a new changes required to pass all tests following the ansible
version bump. Detailed description of changes below:

------------------------------------------------------------------------------------
Fix: Only run sanity and unit tests with the python version in the venv

Only target the version of python3 in the activate virtual environment.
Do not target any other discovered python runtimes.

An update in ansible-test now triggers ansible-test to discover all available
python runtimes and attempt run for all discovered versions. This is not
our use case. We only want to test with the python runtime in the active
virtual environment.
------------------------------------------------------------------------------------
Fix: Install pytest-mock to fix `mock_use_standalone_module` pytest config warning

Fixing `Unknown config option: mock_use_standalone_module` requires
installing of pytest-mock as a requirement and mock too which pytest-mock
depends on.

Exact error being fixed:

```
  /root/venv/lib64/python3.8/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: mock_use_standalone_module

```
------------------------------------------------------------------------------------
Fix: Pylint errors. Address all consider-using-f-string C0209 errors

Following a new release of pylint there is a new error

```
consider-using-f-string: Formatting a regular string which could be a f-string
```

For each line where f-strings are appropriate. This commit makes the
change from `.format` string formatting to using f-strings.
------------------------------------------------------------------------------------
Dev: Add verbose output to ansible-lint

This helps in debugging linting failures as we can
see the last file being linted in the log output.
------------------------------------------------------------------------------------
Fix: ansible-lint version bump to address linting failures

Ansible-lint 4.3.7 addresses linting failures related to

https://github.com/ansible-community/ansible-lint/issues/892

I have not bumped to a version of ansible-lint > 5 due to new linting
checks introduced which have not yet been addressed in code.
I will do so in a separate PR.
------------------------------------------------------------------------------------
Fix: Ansible sanity checks - Disabling of logging for ssh_key_path module arguments is not required

Only the path is logged and not the actual key content.

To disable we add the file and the sanity check, no-log-needed, to the
ignores file. There does not appear to be a more granular way of disabling
other than per file.

See https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html
for more details.
------------------------------------------------------------------------------------
Fix: Ansible sanity check return-syntax-error for os_conversion_host_info module

Documented return type in os_conversion_host_info module was not complete.

Updating the return types of 'str' for the 'address','id', 'name' and 'status' keys
resolves this failure.

Exact error message being fixed:

```
ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.address.type: required key not provided
@ data['openstack_conversion_host']['contains']['address']['type'].
Got None

ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.id.type: required key not provided
@ data['openstack_conversion_host']['contains']['id']['type'].
Got None

ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.name.type: required key not provided
@ data['openstack_conversion_host']['contains']['name']['type'].
Got None

ERROR: plugins/modules/os_conversion_host_info.py:0:0: return-syntax-error: RETURN.openstack_conversion_host.contains.status.type: required key not provided
@ data['openstack_conversion_host']['contains']['status']['type'].
Got None
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check return-syntax-error for read_resources module

Documented return type in read_resources module was not complete.

Updating the return types of 'dict' for the 'info' and 'params' keys
resolves this failure.

Exact error message being fixed:

```
ERROR: plugins/modules/read_resources.py:0:0: return-syntax-error:
RETURN.resources.contains.info.contains: required key not provided
@ data['resources']['contains']['info']['contains']. Got None

ERROR: plugins/modules/read_resources.py:0:0: return-syntax-error:
RETURN.resources.contains.params.contains: required key not provided
@ data['resources']['contains']['params']['contains']. Got None
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check parameter-list-no-elements for argument 'paths'

Argument 'paths' in argument_spec was of type list but the type of
the elements in the list was not defined.

Adding `elements='str'` in code and documentation resolves this sanity check failure.

Exact error message being fixed:

```
ERROR: plugins/modules/validate_resource_files.py:0:0: parameter-list-no-elements:
Argument 'paths' in argument_spec defines type as list but elements is not defined
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check doc-required-mismatch for argument 'log_dir'

Argument 'log_dir' in argument_spec was configured as not required, but was documented
as being required.

Altering the documentation to reflect code fixes this sanity check failure.

Example of exact error message being fixed:

```
ERROR: plugins/modules/import_workload_prelim.py:0:0: doc-required-mismatch:
Argument 'log_dir' in argument_spec is not required, but is documented as being required
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check parameter-list-no-elements for argument 'block_device_mapping'

Argument 'block_device_mapping' in argument_spec was of type list but the type of
the elements in the list was not defined.

Adding `elements='dict'` in code and documentation resolves this sanity check failure.

Exact error message being fixed:

```
ERROR: plugins/modules/import_workload_create_instance.py:0:0:
parameter-list-no-elements:
Argument 'block_device_mapping' in argument_spec defines type as
list but elements is not defined
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check no-log-needed for argument 'ssh_key_path'

Argument 'ssh_key_path' in argument_spec was by default configured to
log but as recommended by the no-log-needed sanity check this path
could indeed be secret.
As such we can mark this argument as no_log=True to remove this
argument's value from any logs.

Example of exact error message being fixed:

```
ERROR: plugins/modules/import_workload_dst_failure_cleanup.py:0:0: no-log-needed:
Argument 'ssh_key_path' in argument_spec could be a secret, though doesn't have `no_log` set
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check doc-required-mismatch for argument 'filters'

Argument 'filters' in argument_spec was configured as not required, but was documented
as being required.

Altering the documentation to reflect code fixes this sanity check failure.

Example of exact error message being fixed:

```
ERROR: plugins/modules/import_keypair.py:0:0: doc-required-mismatch:
Argument 'filters' in argument_spec is not required, but is documented as being required
```
------------------------------------------------------------------------------------
Fix: Ansible sanity check doc-required-mismatch for argument 'auth'

Argument 'auth' in argument_spec was configured not required, but was documented as being required.

Adding 'auth' with required=True solves this check failure.

Exact error message being fixed:

```
ERROR: plugins/modules/export_flavor.py:0:0: doc-required-mismatch:
Argument 'auth' in argument_spec is not required, but is documented as being required
```
------------------------------------------------------------------------------------
Fix: Update the module module 'version_added' to a valid semantic version

New ansible sanity check validates that the 'version_added' is a valid semantic
version. As per https://semver.org/ '2.9' is not but '2.9.0' is

This fixes ansible sanity check module-invalid-version-added errors like:

```
ERROR: plugins/modules/auth_info.py:0:0: module-invalid-version-added:
DOCUMENTATION: version_added ('2.9') is not a valid collection version
(see specification at https://semver.org/): invalid semantic version '2.9'.
```
------------------------------------------------------------------------------------
Fix: Ignore gplv3-license ansible sanity checks for newer ansible versions

Following bump in default ansible version we need to continue to ignore
the gplv3-license sanity checks.

ignore-2.10.txt is used for ansible versions reporting version 2.10
like ansible 3.4.0 whose dependency package ansible-base is version 2.10

ignore-2.11.txt is used for ansible versions reporting version 2.11
like ansible 4.5.0 whose dependency package ansible-core is version 2.11