Dev: Use Fedora base container image from quay.io
Originally we used images from registry.fedoraproject.org but it was
often down. So we switched to docker.io registry, but we're starting
to get rate-limited:

Error: error creating build container: Error initializing source
docker://fedora:33: Error reading manifest 33 in
docker.io/library/fedora: toomanyrequests: You have reached your pull
rate limit. You may increase the limit by authenticating and
upgrading: https://www.docker.com/increase-rate-limit

So let's try quay.io.